name: COBOL Check Automation

on:
  workflow_dispatch:

jobs:
  cobol-check:
    runs-on: ubuntu-latest  # or windows-latest if on Windows, but needs network access

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Make COBOL script executable
      run: chmod +x .github/scripts/zowe_operations.sh

    - name: Run COBOL Check script using default profile
      run: ./.github/scripts/zowe_operations.sh
